/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTeachersRouteImport } from './routes/app.teachers'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppFeesRouteImport } from './routes/app.fees'
import { Route as AppExamsRouteImport } from './routes/app.exams'
import { Route as AppClassesRouteImport } from './routes/app.classes'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAnnouncementsRouteImport } from './routes/app.announcements'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/classes': typeof AppClassesRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/classes': typeof AppClassesRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/classes': typeof AppClassesRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/classes'
    | '/app/exams'
    | '/app/fees'
    | '/app/students'
    | '/app/teachers'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/classes'
    | '/app/exams'
    | '/app/fees'
    | '/app/students'
    | '/app/teachers'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/classes'
    | '/app/exams'
    | '/app/fees'
    | '/app/students'
    | '/app/teachers'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teachers': {
      id: '/app/teachers'
      path: '/teachers'
      fullPath: '/app/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fees': {
      id: '/app/fees'
      path: '/fees'
      fullPath: '/app/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams': {
      id: '/app/exams'
      path: '/exams'
      fullPath: '/app/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes': {
      id: '/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppClassesRoute: typeof AppClassesRoute
  AppExamsRoute: typeof AppExamsRoute
  AppFeesRoute: typeof AppFeesRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppClassesRoute: AppClassesRoute,
  AppExamsRoute: AppExamsRoute,
  AppFeesRoute: AppFeesRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
